name: ci
on:
  pull_request:
    paths:
      - ".github/workflows/collector.yml"

jobs:
  context:
    runs-on: ubuntu-20.04
    name: Github context
    steps:
      - name: Github context
        run: |
          jq . <<EOF
            ${{ toJSON(github) }}
          EOF

  always-success:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 0"

  always-fails:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 1"

  always-timeout:
    runs-on: ubuntu-20.04
    timeout: 1
    steps:
      - run: "sleep 5"

  collector-job:
    # This is necessary since a failed/skipped job would cause this job to be skipped
    if: always()
    needs: [always-success, always-timeout]
    name: Approach A - all passing
    runs-on: ubuntu-20.04
    steps:
      - name: Check for any failures
        if: contains(needs.*.result, 'failure')
        run: "exit 2"

      - name: Check for any failures
        if: contains(needs.*.result, 'failure')
        run: "exit 2"

  # # This one includes a job that is skipped
  # approach-a-skip:
  #   # We should never skip this job
  #   needs: [one, three]
  #   # The name has to match the name from the next job
  #   name: Approach A - one skipped
  #   runs-on: ubuntu-20.04
  #   # This is necessary since a failed/skipped job would cause this job to be skipped
  #   if: always()
  #   steps:
  #     - name: Check for any failures
  #       if: contains(needs.*.result, 'failure')
  #       run: "exit 2"

  # # This one includes a job that is skipped
  # approach-a-failure:
  #   # We should never skip this job
  #   needs: [one, two, three, four]
  #   # The name has to match the name from the next job
  #   name: Approach A - one failing
  #   runs-on: ubuntu-20.04
  #   # This is necessary since a failed/skipped job would cause this job to be skipped
  #   if: always()
  #   steps:
  #     - name: Check for any failures
  #       if: contains(needs.*.result, 'failure')
  #       run: "exit 2"
