name: collector
on:
  pull_request:
    paths:
      - ".github/workflows/collector.yml"

jobs:
  context:
    runs-on: ubuntu-20.04
    name: Github context
    steps:
      - name: Github context
        run: |
          jq . <<EOF
            ${{ toJSON(github) }}
          EOF

  awlays-succeeds:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 0"

  always-fails:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 1"

  always-timesout:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - run: "sleep 65"

  collector-job-with-both:
    # This is necessary since a failed/skipped job would cause this job to be skipped
    if: always()
    needs: [awlays-succeeds, awlays-fails, always-timesout]
    name: Collector job
    runs-on: ubuntu-20.04
    steps:
      # run this action to get the workflow conclusion
      # You can get the conclusion via env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@3ac32f35e946d5298758591b6a14abc8b9563ec0

      - name: Output
        run: env | sort

      - name: Check for any failures
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: "exit 2"

  # collector-job-with-timeout:
  #   # This is necessary since a failed/skipped job would cause this job to be skipped
  #   if: always()
  #   needs: [awlays-succeeds, always-timesout]
  #   name: Collector job
  #   runs-on: ubuntu-20.04
  #   steps:
  #     # run this action to get the workflow conclusion
  #     # You can get the conclusion via env (env.WORKFLOW_CONCLUSION)
  #     - uses: technote-space/workflow-conclusion-action@3ac32f35e946d5298758591b6a14abc8b9563ec0

  #     - name: Output
  #       run: env | sort

  #     - name: Check for any failures
  #       if: env.WORKFLOW_CONCLUSION == 'failure'
  #       run: "exit 2"

  # collector-job-with-failure:
  #   # This is necessary since a failed/skipped job would cause this job to be skipped
  #   if: always()
  #   needs: [awlays-succeeds, awlays-fails]
  #   name: Collector job
  #   runs-on: ubuntu-20.04
  #   steps:
  #     # run this action to get the workflow conclusion
  #     # You can get the conclusion via env (env.WORKFLOW_CONCLUSION)
  #     - uses: technote-space/workflow-conclusion-action@3ac32f35e946d5298758591b6a14abc8b9563ec0

  #     - name: Output
  #       run: env | sort

  #     - name: Check for any failures
  #       if: env.WORKFLOW_CONCLUSION == 'failure'
  #       run: "exit 2"

  # # This one includes a job that is skipped
  # approach-a-skip:
  #   # We should never skip this job
  #   needs: [one, three]
  #   # The name has to match the name from the next job
  #   name: Approach A - one skipped
  #   runs-on: ubuntu-20.04
  #   # This is necessary since a failed/skipped job would cause this job to be skipped
  #   if: always()
  #   steps:
  #     - name: Check for any failures
  #       if: contains(needs.*.result, 'failure')
  #       run: "exit 2"

  # # This one includes a job that is skipped
  # approach-a-failure:
  #   # We should never skip this job
  #   needs: [one, two, three, four]
  #   # The name has to match the name from the next job
  #   name: Approach A - one failing
  #   runs-on: ubuntu-20.04
  #   # This is necessary since a failed/skipped job would cause this job to be skipped
  #   if: always()
  #   steps:
  #     - name: Check for any failures
  #       if: contains(needs.*.result, 'failure')
  #       run: "exit 2"
