on:
  push:
    branches:
      - master
  pull_request:

jobs:
  boo:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 1"

  great:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 0"

  what:
    runs-on: ubuntu-20.04
    # This job always skips
    if: github.head_repository.full_name == 'getsentry/sentry'
    steps:
      - run: "exit 0"

  collector:
    # If all the jobs pass, this check will pass
    # If one of the jobs is skipped or failed, this check will be skipped *and*
    # counting to have met the criteria for Required jobs
    needs: [boo, great, what]
    # The name has to match the name from the next job
    name: Required Foo
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "Hooray!"'

  collector-failed:
    needs: [boo, great]
    # It needs to match the name from the previous job
    name: Required Foo
    runs-on: ubuntu-20.04
    # This will make sure that the check turns red rather than skipped
    # Since a Required check being skipped counts as having met the requirement
    if: failure()
    steps:
      - run: "exit 1"
