name: yay
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  one:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 0"

  two:
    runs-on: ubuntu-20.04
    steps:
      - run: "exit 0"

  collector:
    # If all the jobs pass, this check will pass
    # If one of the jobs is skipped or failed, this check will be skipped *and*
    # counting to have met the criteria for Required jobs
    needs: [one, two]
    # The name has to match the name from the next job
    name: Required Bar
    runs-on: ubuntu-20.04
    # This is necessary since a failed/skipped job would cause this job to be skipped
    if: always()
    steps:
      - name: Check for failures
        # This sadly requires duplication of the list declated in needs
        if: needs.one.result != 'success' || needs.two.result != 'success'
        run: "exit 2"
